In [2]:
import numpy as np

In [4]:
x = np.array([2, 3, 5, 7, 10])

In [5]:
print(x)

[ 2  3  5  7 10]


In [6]:
type(x)

numpy.ndarray

In [13]:
x=np.array(([2,5,7,10]),dtype="float")

In [14]:
type(x)

numpy.ndarray

In [16]:
x = np.zeros((3, 4))

In [17]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
x=np.ones((3,4))

In [19]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
x = np.full((3, 4), 7)

In [24]:
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [25]:
x=np.eye(3,3)

In [26]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
x = np.arange(2, 10, 3)

In [30]:
print(x)

[2 5 8]


In [32]:
x = np.linspace(7, 10, 10)

In [33]:
print(x)

[ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]
