In [1]:
import numpy as np

In [2]:
x= np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [7]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print("value at [0][0] and [0][1] : ",x[0:1,0:2])

value at [0][0] and [0][1] :  [[0 1]]


In [11]:
print("value at[0][1] , [0][2] , [0][3] :",x[0:1,1:4])

value at[0][1] , [0][2] , [0][3] : [[1 2 3]]


In [22]:
print("value at[1][0] :",x[1:2, 0:1])

value at[1][0] : [[4]]


In [15]:
print("value at[1][1],[1,2],[1,3] :",x[1:2,1:4])

value at[1][1],[1,2],[1,3] : [[5 6 7]]


In [23]:
print(x[1:3,1:4])

[[ 5  6  7]
 [ 9 10 11]]


In [30]:
y=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,53]])

In [31]:
print(y)

[[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 53]]


In [32]:
print("value as 35,36,43,47:",y[1:3,1:3])

value as 35,36,43,47: [[35 36]
 [43 47]]


In [33]:
print(y[2: ,1: ])

[[43 47 50]
 [51 52 53]]


In [34]:
print(y[0:2 ,2: ])

[[24 25]
 [36 40]]
